resolver: nightly-2016-07-03

packages:
- t3-core
- t3-bot
- t3-game
- t3-game-console
- t3-server

extra-deps:
- text-conversions-0.3.0
- hashmap-1.3.1.1
- test-fixture-0.4.0.0

#flags:
#  t3-server:
#    library-only: false
#    dev: false
